version: 2.1
jobs:
  gcc:
    resource_class: large
    docker:
      - image: debian:testing-slim
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    environment:
      CFLAGS: -Wextra -Werror -march=native
      CXXFLAGS: -Wextra -Werror -march=native
    steps:
      - run: apt-get update && apt-get install -y git ssh ninja-build python3-pip python3-setuptools python3-wheel gcovr gcc g++
      - checkout
      - run: cat /proc/cpuinfo /proc/meminfo
      - run: pip3 install meson
      - run: CC=gcc CXX=g++ CFLAGS=-Wno-error=stringop-overread CXXFLAGS=-Wno-error=stringop-overread /usr/local/bin/meson setup build -Db_coverage=true
      - run: ninja -C build -v -j 5
      - run: ninja -C build -v test

  clang:
    resource_class: large
    docker:
      - image: debian:testing-slim
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    environment:
      CFLAGS: -Weverything -Werror -march=native
      CXXFLAGS: -Weverything -Werror -march=native
    steps:
      - run: apt-get update && apt-get install -y git ssh ninja-build python3-pip python3-setuptools python3-wheel gcovr clang
      - checkout
      - run: cat /proc/cpuinfo /proc/meminfo
      - run: pip3 install meson
      - run: CC=clang CXX=clang++ /usr/local/bin/meson setup build -Db_coverage=true
      - run: ninja -C build -v -j 5
      - run: ninja -C build -v test

  loongson:
    resource_class: large
    docker:
      - image: debian:testing-slim
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    environment:
      CC: gcc-mips64el-linux-gnuabi64
      CXX: g++-mips64el-linux-gnuabi64
      CFLAGS: -Wextra -Werror
      CXXFLAGS: -Wextra -Werror
    steps:
      - run: apt-get update && apt-get install -y git ssh ninja-build python3-pip python3-setuptools python3-wheel gcovr gcc-mips64el-linux-gnuabi64 g++-mips64el-linux-gnuabi64 qemu-user-static libc6-mips64el-cross
      - checkout
      - run: cat /proc/cpuinfo /proc/meminfo
      - run: pip3 install meson
      - run: /usr/local/bin/meson setup build -Db_coverage=true --cross-file=docker/cross-files/loongson-gcc.cross
      - run: ninja -C build -v -j 5
      # - run: ninja -C build -v -j 3 test

  i686:
    resource_class: large
    docker:
      - image: debian:testing-slim
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    environment:
      CFLAGS: -Wextra -Werror -march=native
      CXXFLAGS: -Wextra -Werror -march=native
    steps:
      - run: apt-get update && apt-get install -y git ssh ninja-build python3-pip python3-setuptools python3-wheel gcovr {gcc,g++}-i686-linux-gnu libc6-i386-cross
      - checkout
      - run:
          name: System Information
          command: cat /proc/cpuinfo /proc/meminfo
      - run: pip3 install meson
      - run: CC=x86_64-linux-gnu-gcc CXX=x86_64-linux-gnu-g++ /usr/local/bin/meson setup build -Db_coverage=true
      - run: ninja -C build -v -j 5
      - run: ninja -C build -v test

workflows:
  version: 2
  test:
    jobs:
      - gcc:
          filters:
            branches:
              ignore:
              - master
              - /^ci/(?!circleci).*$/
      - clang:
          filters:
            branches:
              ignore:
              - master
              - /^ci/(?!circleci).*$/
      - loongson:
          filters:
            branches:
              ignore:
              - master
              - /^ci/(?!circleci).*$/
      - i686:
          filters:
            branches:
              ignore:
              - master
              - /^ci/(?!circleci).*$/
